#############################################################################
# Makefile for building: TDB2
# Generated by qmake (2.01a) (Qt 4.8.6) on: zo aug. 21 14:37:34 2016
# Project:  TDB2.1.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile TDB2.1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtSql -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		TDBAccount.cpp \
		TDBAdminAdmin.cpp \
		TDBAdminCreation.cpp \
		TDBAdminList.cpp \
		TDBAdminModification.cpp \
		TDBApplication.cpp \
		TDBAuthDialog.cpp \
		TDBBatchDialog.cpp \
		TDBBinetAdmin.cpp \
		TDBBinetList.cpp \
		TDBClopes.cpp \
		TDBClopesAdmin.cpp \
		TDBClopesCreation.cpp \
		TDBClopesList.cpp \
		TDBClopesModification.cpp \
		TDBDatabase.cpp \
		TDBExceptions.cpp \
		TDBHistory.cpp \
		TDBMainWindow.cpp \
		TDBMainWindow_admin.cpp \
		TDBPasswordChange.cpp \
		TDBPasswordDialog.cpp \
		TDBRefillDialog.cpp \
		TDBSearch.cpp \
		TDBSearchList.cpp \
		TDBTransactionDialog.cpp \
		TDBTransfertDialog.cpp \
		TDBTrigrammeCreationDialog.cpp \
		TDBTrigrammeDialog.cpp \
		TDBTrigrammeModificationDialog.cpp \
		TDBTrigrammeValidator.cpp moc_TDBAdminAdmin.cpp \
		moc_TDBAdminCreation.cpp \
		moc_TDBAdminModification.cpp \
		moc_TDBApplication.cpp \
		moc_TDBAuthDialog.cpp \
		moc_TDBBatchDialog.cpp \
		moc_TDBBinetAdmin.cpp \
		moc_TDBClopes.cpp \
		moc_TDBClopesAdmin.cpp \
		moc_TDBClopesCreation.cpp \
		moc_TDBClopesModification.cpp \
		moc_TDBMainWindow.cpp \
		moc_TDBPasswordChange.cpp \
		moc_TDBPasswordDialog.cpp \
		moc_TDBRefillDialog.cpp \
		moc_TDBSearch.cpp \
		moc_TDBTransactionDialog.cpp \
		moc_TDBTransfertDialog.cpp \
		moc_TDBTrigrammeCreationDialog.cpp \
		moc_TDBTrigrammeDialog.cpp \
		moc_TDBTrigrammeModificationDialog.cpp
OBJECTS       = main.o \
		TDBAccount.o \
		TDBAdminAdmin.o \
		TDBAdminCreation.o \
		TDBAdminList.o \
		TDBAdminModification.o \
		TDBApplication.o \
		TDBAuthDialog.o \
		TDBBatchDialog.o \
		TDBBinetAdmin.o \
		TDBBinetList.o \
		TDBClopes.o \
		TDBClopesAdmin.o \
		TDBClopesCreation.o \
		TDBClopesList.o \
		TDBClopesModification.o \
		TDBDatabase.o \
		TDBExceptions.o \
		TDBHistory.o \
		TDBMainWindow.o \
		TDBMainWindow_admin.o \
		TDBPasswordChange.o \
		TDBPasswordDialog.o \
		TDBRefillDialog.o \
		TDBSearch.o \
		TDBSearchList.o \
		TDBTransactionDialog.o \
		TDBTransfertDialog.o \
		TDBTrigrammeCreationDialog.o \
		TDBTrigrammeDialog.o \
		TDBTrigrammeModificationDialog.o \
		TDBTrigrammeValidator.o \
		moc_TDBAdminAdmin.o \
		moc_TDBAdminCreation.o \
		moc_TDBAdminModification.o \
		moc_TDBApplication.o \
		moc_TDBAuthDialog.o \
		moc_TDBBatchDialog.o \
		moc_TDBBinetAdmin.o \
		moc_TDBClopes.o \
		moc_TDBClopesAdmin.o \
		moc_TDBClopesCreation.o \
		moc_TDBClopesModification.o \
		moc_TDBMainWindow.o \
		moc_TDBPasswordChange.o \
		moc_TDBPasswordDialog.o \
		moc_TDBRefillDialog.o \
		moc_TDBSearch.o \
		moc_TDBTransactionDialog.o \
		moc_TDBTransfertDialog.o \
		moc_TDBTrigrammeCreationDialog.o \
		moc_TDBTrigrammeDialog.o \
		moc_TDBTrigrammeModificationDialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TDB2.1.pro
QMAKE_TARGET  = TDB2
DESTDIR       = 
TARGET        = TDB2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TDB2.1.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile TDB2.1.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile TDB2.1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TDB21.0.0 || $(MKDIR) .tmp/TDB21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TDB21.0.0/ && $(COPY_FILE) --parents TDBAccount.h TDBAdminAdmin.h TDBAdminCreation.h TDBAdminList.h TDBAdminModification.h TDBApplication.h TDBAuth.h TDBAuthDialog.h TDBBatchDialog.h TDBBinetAdmin.h TDBBinetList.h TDBClopes.h TDBClopesAdmin.h TDBClopesCreation.h TDBClopesList.h TDBClopesModification.h TDBDatabase.h TDBExceptions.h TDBHistory.h TDBMainWindow.h TDBPasswordChange.h TDBPasswordDialog.h TDBRefillDialog.h TDBSearch.h TDBSearchList.h TDBTransactionDialog.h TDBTransfertDialog.h TDBTrigrammeCreationDialog.h TDBTrigrammeDialog.h TDBTrigrammeModificationDialog.h TDBTrigrammeValidator.h .tmp/TDB21.0.0/ && $(COPY_FILE) --parents main.cpp TDBAccount.cpp TDBAdminAdmin.cpp TDBAdminCreation.cpp TDBAdminList.cpp TDBAdminModification.cpp TDBApplication.cpp TDBAuthDialog.cpp TDBBatchDialog.cpp TDBBinetAdmin.cpp TDBBinetList.cpp TDBClopes.cpp TDBClopesAdmin.cpp TDBClopesCreation.cpp TDBClopesList.cpp TDBClopesModification.cpp TDBDatabase.cpp TDBExceptions.cpp TDBHistory.cpp TDBMainWindow.cpp TDBMainWindow_admin.cpp TDBPasswordChange.cpp TDBPasswordDialog.cpp TDBRefillDialog.cpp TDBSearch.cpp TDBSearchList.cpp TDBTransactionDialog.cpp TDBTransfertDialog.cpp TDBTrigrammeCreationDialog.cpp TDBTrigrammeDialog.cpp TDBTrigrammeModificationDialog.cpp TDBTrigrammeValidator.cpp .tmp/TDB21.0.0/ && (cd `dirname .tmp/TDB21.0.0` && $(TAR) TDB21.0.0.tar TDB21.0.0 && $(COMPRESS) TDB21.0.0.tar) && $(MOVE) `dirname .tmp/TDB21.0.0`/TDB21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TDB21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TDBAdminAdmin.cpp moc_TDBAdminCreation.cpp moc_TDBAdminModification.cpp moc_TDBApplication.cpp moc_TDBAuthDialog.cpp moc_TDBBatchDialog.cpp moc_TDBBinetAdmin.cpp moc_TDBClopes.cpp moc_TDBClopesAdmin.cpp moc_TDBClopesCreation.cpp moc_TDBClopesModification.cpp moc_TDBMainWindow.cpp moc_TDBPasswordChange.cpp moc_TDBPasswordDialog.cpp moc_TDBRefillDialog.cpp moc_TDBSearch.cpp moc_TDBTransactionDialog.cpp moc_TDBTransfertDialog.cpp moc_TDBTrigrammeCreationDialog.cpp moc_TDBTrigrammeDialog.cpp moc_TDBTrigrammeModificationDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TDBAdminAdmin.cpp moc_TDBAdminCreation.cpp moc_TDBAdminModification.cpp moc_TDBApplication.cpp moc_TDBAuthDialog.cpp moc_TDBBatchDialog.cpp moc_TDBBinetAdmin.cpp moc_TDBClopes.cpp moc_TDBClopesAdmin.cpp moc_TDBClopesCreation.cpp moc_TDBClopesModification.cpp moc_TDBMainWindow.cpp moc_TDBPasswordChange.cpp moc_TDBPasswordDialog.cpp moc_TDBRefillDialog.cpp moc_TDBSearch.cpp moc_TDBTransactionDialog.cpp moc_TDBTransfertDialog.cpp moc_TDBTrigrammeCreationDialog.cpp moc_TDBTrigrammeDialog.cpp moc_TDBTrigrammeModificationDialog.cpp
moc_TDBAdminAdmin.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAdminModification.h \
		TDBAuth.h \
		TDBAdminCreation.h \
		TDBAdminList.h \
		TDBAdminAdmin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBAdminAdmin.h -o moc_TDBAdminAdmin.cpp

moc_TDBAdminCreation.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h \
		TDBAdminCreation.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBAdminCreation.h -o moc_TDBAdminCreation.cpp

moc_TDBAdminModification.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h \
		TDBAdminModification.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBAdminModification.h -o moc_TDBAdminModification.cpp

moc_TDBApplication.cpp: TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBApplication.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBApplication.h -o moc_TDBApplication.cpp

moc_TDBAuthDialog.cpp: TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBAuthDialog.h -o moc_TDBAuthDialog.cpp

moc_TDBBatchDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBBatchDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBBatchDialog.h -o moc_TDBBatchDialog.cpp

moc_TDBBinetAdmin.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBBinetList.h \
		TDBAuth.h \
		TDBBinetAdmin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBBinetAdmin.h -o moc_TDBBinetAdmin.cpp

moc_TDBClopes.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBClopes.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBClopes.h -o moc_TDBClopes.cpp

moc_TDBClopesAdmin.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBAuth.h \
		TDBClopesList.h \
		TDBClopesAdmin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBClopesAdmin.h -o moc_TDBClopesAdmin.cpp

moc_TDBClopesCreation.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h \
		TDBClopesCreation.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBClopesCreation.h -o moc_TDBClopesCreation.cpp

moc_TDBClopesModification.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBClopesModification.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBClopesModification.h -o moc_TDBClopesModification.cpp

moc_TDBMainWindow.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBAdminAdmin.h \
		TDBAdminModification.h \
		TDBAdminCreation.h \
		TDBAdminList.h \
		TDBBatchDialog.h \
		TDBBinetAdmin.h \
		TDBBinetList.h \
		TDBClopes.h \
		TDBClopesAdmin.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBClopesList.h \
		TDBHistory.h \
		TDBPasswordChange.h \
		TDBRefillDialog.h \
		TDBSearch.h \
		TDBSearchList.h \
		TDBTransactionDialog.h \
		TDBTransfertDialog.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h \
		TDBTrigrammeCreationDialog.h \
		TDBTrigrammeModificationDialog.h \
		TDBMainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBMainWindow.h -o moc_TDBMainWindow.cpp

moc_TDBPasswordChange.cpp: TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBApplication.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBPasswordChange.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBPasswordChange.h -o moc_TDBPasswordChange.cpp

moc_TDBPasswordDialog.cpp: TDBPasswordDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBPasswordDialog.h -o moc_TDBPasswordDialog.cpp

moc_TDBRefillDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBRefillDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBRefillDialog.h -o moc_TDBRefillDialog.cpp

moc_TDBSearch.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBSearchList.h \
		TDBAuth.h \
		TDBSearch.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBSearch.h -o moc_TDBSearch.cpp

moc_TDBTransactionDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTransactionDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBTransactionDialog.h -o moc_TDBTransactionDialog.cpp

moc_TDBTransfertDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h \
		TDBTransfertDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBTransfertDialog.h -o moc_TDBTransfertDialog.cpp

moc_TDBTrigrammeCreationDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBTrigrammeCreationDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBTrigrammeCreationDialog.h -o moc_TDBTrigrammeCreationDialog.cpp

moc_TDBTrigrammeDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h \
		TDBTrigrammeDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBTrigrammeDialog.h -o moc_TDBTrigrammeDialog.cpp

moc_TDBTrigrammeModificationDialog.cpp: TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBTrigrammeModificationDialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) TDBTrigrammeModificationDialog.h -o moc_TDBTrigrammeModificationDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBMainWindow.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBAdminAdmin.h \
		TDBAdminModification.h \
		TDBAdminCreation.h \
		TDBAdminList.h \
		TDBBatchDialog.h \
		TDBBinetAdmin.h \
		TDBBinetList.h \
		TDBClopes.h \
		TDBClopesAdmin.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBClopesList.h \
		TDBHistory.h \
		TDBPasswordChange.h \
		TDBRefillDialog.h \
		TDBSearch.h \
		TDBSearchList.h \
		TDBTransactionDialog.h \
		TDBTransfertDialog.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h \
		TDBTrigrammeCreationDialog.h \
		TDBTrigrammeModificationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

TDBAccount.o: TDBAccount.cpp TDBAccount.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAccount.o TDBAccount.cpp

TDBAdminAdmin.o: TDBAdminAdmin.cpp TDBAdminAdmin.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAdminModification.h \
		TDBAuth.h \
		TDBAdminCreation.h \
		TDBAdminList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAdminAdmin.o TDBAdminAdmin.cpp

TDBAdminCreation.o: TDBAdminCreation.cpp TDBAdminCreation.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAdminCreation.o TDBAdminCreation.cpp

TDBAdminList.o: TDBAdminList.cpp TDBAdminList.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBApplication.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAdminList.o TDBAdminList.cpp

TDBAdminModification.o: TDBAdminModification.cpp TDBAdminModification.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAdminModification.o TDBAdminModification.cpp

TDBApplication.o: TDBApplication.cpp TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBApplication.o TDBApplication.cpp

TDBAuthDialog.o: TDBAuthDialog.cpp TDBAuthDialog.h \
		TDBDatabase.h \
		TDBPasswordDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBAuthDialog.o TDBAuthDialog.cpp

TDBBatchDialog.o: TDBBatchDialog.cpp TDBBatchDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBBatchDialog.o TDBBatchDialog.cpp

TDBBinetAdmin.o: TDBBinetAdmin.cpp TDBBinetAdmin.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBBinetList.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBBinetAdmin.o TDBBinetAdmin.cpp

TDBBinetList.o: TDBBinetList.cpp TDBBinetList.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBBinetList.o TDBBinetList.cpp

TDBClopes.o: TDBClopes.cpp TDBClopes.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBClopes.o TDBClopes.cpp

TDBClopesAdmin.o: TDBClopesAdmin.cpp TDBClopesAdmin.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBAuth.h \
		TDBClopesList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBClopesAdmin.o TDBClopesAdmin.cpp

TDBClopesCreation.o: TDBClopesCreation.cpp TDBClopesCreation.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBClopesCreation.o TDBClopesCreation.cpp

TDBClopesList.o: TDBClopesList.cpp TDBClopesList.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBClopesList.o TDBClopesList.cpp

TDBClopesModification.o: TDBClopesModification.cpp TDBClopesModification.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBClopesModification.o TDBClopesModification.cpp

TDBDatabase.o: TDBDatabase.cpp TDBDatabase.h \
		TDBPasswordDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBDatabase.o TDBDatabase.cpp

TDBExceptions.o: TDBExceptions.cpp TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBExceptions.o TDBExceptions.cpp

TDBHistory.o: TDBHistory.cpp TDBHistory.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBHistory.o TDBHistory.cpp

TDBMainWindow.o: TDBMainWindow.cpp TDBMainWindow.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBAdminAdmin.h \
		TDBAdminModification.h \
		TDBAdminCreation.h \
		TDBAdminList.h \
		TDBBatchDialog.h \
		TDBBinetAdmin.h \
		TDBBinetList.h \
		TDBClopes.h \
		TDBClopesAdmin.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBClopesList.h \
		TDBHistory.h \
		TDBPasswordChange.h \
		TDBRefillDialog.h \
		TDBSearch.h \
		TDBSearchList.h \
		TDBTransactionDialog.h \
		TDBTransfertDialog.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h \
		TDBTrigrammeCreationDialog.h \
		TDBTrigrammeModificationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBMainWindow.o TDBMainWindow.cpp

TDBMainWindow_admin.o: TDBMainWindow_admin.cpp TDBMainWindow.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAccount.h \
		TDBAuth.h \
		TDBAdminAdmin.h \
		TDBAdminModification.h \
		TDBAdminCreation.h \
		TDBAdminList.h \
		TDBBatchDialog.h \
		TDBBinetAdmin.h \
		TDBBinetList.h \
		TDBClopes.h \
		TDBClopesAdmin.h \
		TDBClopesModification.h \
		TDBClopesCreation.h \
		TDBClopesList.h \
		TDBHistory.h \
		TDBPasswordChange.h \
		TDBRefillDialog.h \
		TDBSearch.h \
		TDBSearchList.h \
		TDBTransactionDialog.h \
		TDBTransfertDialog.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h \
		TDBTrigrammeCreationDialog.h \
		TDBTrigrammeModificationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBMainWindow_admin.o TDBMainWindow_admin.cpp

TDBPasswordChange.o: TDBPasswordChange.cpp TDBPasswordChange.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBApplication.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBPasswordChange.o TDBPasswordChange.cpp

TDBPasswordDialog.o: TDBPasswordDialog.cpp TDBPasswordDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBPasswordDialog.o TDBPasswordDialog.cpp

TDBRefillDialog.o: TDBRefillDialog.cpp TDBRefillDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBRefillDialog.o TDBRefillDialog.cpp

TDBSearch.o: TDBSearch.cpp TDBSearch.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBSearchList.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBSearch.o TDBSearch.cpp

TDBSearchList.o: TDBSearchList.cpp TDBSearchList.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBSearchList.o TDBSearchList.cpp

TDBTransactionDialog.o: TDBTransactionDialog.cpp TDBTransactionDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTransactionDialog.o TDBTransactionDialog.cpp

TDBTransfertDialog.o: TDBTransfertDialog.cpp TDBTransfertDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeDialog.h \
		TDBTrigrammeValidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTransfertDialog.o TDBTransfertDialog.cpp

TDBTrigrammeCreationDialog.o: TDBTrigrammeCreationDialog.cpp TDBTrigrammeCreationDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h \
		TDBAccount.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTrigrammeCreationDialog.o TDBTrigrammeCreationDialog.cpp

TDBTrigrammeDialog.o: TDBTrigrammeDialog.cpp TDBTrigrammeDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTrigrammeDialog.o TDBTrigrammeDialog.cpp

TDBTrigrammeModificationDialog.o: TDBTrigrammeModificationDialog.cpp TDBTrigrammeModificationDialog.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h \
		TDBTrigrammeValidator.h \
		TDBAccount.h \
		TDBAuth.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTrigrammeModificationDialog.o TDBTrigrammeModificationDialog.cpp

TDBTrigrammeValidator.o: TDBTrigrammeValidator.cpp TDBTrigrammeValidator.h \
		TDBApplication.h \
		TDBDatabase.h \
		TDBPasswordDialog.h \
		TDBAuthDialog.h \
		TDBExceptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TDBTrigrammeValidator.o TDBTrigrammeValidator.cpp

moc_TDBAdminAdmin.o: moc_TDBAdminAdmin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBAdminAdmin.o moc_TDBAdminAdmin.cpp

moc_TDBAdminCreation.o: moc_TDBAdminCreation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBAdminCreation.o moc_TDBAdminCreation.cpp

moc_TDBAdminModification.o: moc_TDBAdminModification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBAdminModification.o moc_TDBAdminModification.cpp

moc_TDBApplication.o: moc_TDBApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBApplication.o moc_TDBApplication.cpp

moc_TDBAuthDialog.o: moc_TDBAuthDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBAuthDialog.o moc_TDBAuthDialog.cpp

moc_TDBBatchDialog.o: moc_TDBBatchDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBBatchDialog.o moc_TDBBatchDialog.cpp

moc_TDBBinetAdmin.o: moc_TDBBinetAdmin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBBinetAdmin.o moc_TDBBinetAdmin.cpp

moc_TDBClopes.o: moc_TDBClopes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBClopes.o moc_TDBClopes.cpp

moc_TDBClopesAdmin.o: moc_TDBClopesAdmin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBClopesAdmin.o moc_TDBClopesAdmin.cpp

moc_TDBClopesCreation.o: moc_TDBClopesCreation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBClopesCreation.o moc_TDBClopesCreation.cpp

moc_TDBClopesModification.o: moc_TDBClopesModification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBClopesModification.o moc_TDBClopesModification.cpp

moc_TDBMainWindow.o: moc_TDBMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBMainWindow.o moc_TDBMainWindow.cpp

moc_TDBPasswordChange.o: moc_TDBPasswordChange.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBPasswordChange.o moc_TDBPasswordChange.cpp

moc_TDBPasswordDialog.o: moc_TDBPasswordDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBPasswordDialog.o moc_TDBPasswordDialog.cpp

moc_TDBRefillDialog.o: moc_TDBRefillDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBRefillDialog.o moc_TDBRefillDialog.cpp

moc_TDBSearch.o: moc_TDBSearch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBSearch.o moc_TDBSearch.cpp

moc_TDBTransactionDialog.o: moc_TDBTransactionDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBTransactionDialog.o moc_TDBTransactionDialog.cpp

moc_TDBTransfertDialog.o: moc_TDBTransfertDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBTransfertDialog.o moc_TDBTransfertDialog.cpp

moc_TDBTrigrammeCreationDialog.o: moc_TDBTrigrammeCreationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBTrigrammeCreationDialog.o moc_TDBTrigrammeCreationDialog.cpp

moc_TDBTrigrammeDialog.o: moc_TDBTrigrammeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBTrigrammeDialog.o moc_TDBTrigrammeDialog.cpp

moc_TDBTrigrammeModificationDialog.o: moc_TDBTrigrammeModificationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TDBTrigrammeModificationDialog.o moc_TDBTrigrammeModificationDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

